### PR TITLE
contrib: add helper script to build the windows port

### PR DESCRIPTION
**Pull request by sledz**
Instead of just document the steps needed to build the KMS windows port
we now provide a little helper script for this.

In addition we pin the revisions of used external repositories to
verified versions.

Signed-off-by: Steffen Sledz <sledz@dresearch-fe.de>

### CODE REVIEW

**Comment by sledz** [comment]
It would be great if this pull request could be reviewed (and hopefully accepted) soon.

It could help us very much upgrading to Kurento 6.6.1 in a determined way, which we like to do in the next days (6.6.1 fixes at least one bad bug related to PlayerEndpoint).

Thx

**Comment by kirushyk** [comment]
Have you tested it? If it shows good results on fresh system, I can believe you & accept it. I can not test it myself now.

**Comment by sledz** [comment]
Yes. We use this for the daily work.

**Comment by kirushyk** [comment]
Okay then :-)

**Comment by sledz** [comment]
BTW: Do you have plans to upgrade from 6.4 to 6.6.1?

**Comment by kirushyk** [comment]
At this moment I can not dedicate my time to this project. If you can help it would be nice.

**Comment by sledz** [comment]
OK, we'll try our best. ;-)

**Comment by kirushyk** [comment]
If you need any assistance - feel free to ping me.

**Pull request merged**
